# Generated by Django 3.0.3 on 2020-03-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppng1',
            new_name='topping1',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='toppng2',
            new_name='topping2',
        ),
    ]
